name: braintv_behav
dependencies:
- backports.shutil_get_terminal_size=1.0.0=py27_0
- backports_abc=0.4=py27_0
- cairo=1.12.18=8
- certifi=2017.1.23=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.10=py27_0
- enum34=1.1.6=py27_1
- fontconfig=2.11.1=3
- freetype=2.6.3=1
- functools32=3.2.3.2=py27_1
- gettext=0.19.7=1
- glib=2.48.0=4
- graphviz=2.38.0=3
- harfbuzz=1.0.6=0
- hdf5=1.8.17=7
- icu=56.1=4
- ipykernel=4.5.1=py27_0
- ipython=5.1.0=py27_1
- ipython_genutils=0.1.0=py27_0
- jpeg=9b=0
- jupyter_client=4.4.0=py27_0
- jupyter_core=4.2.0=py27_0
- libffi=3.2.1=2
- libgfortran=3.0.0=1
- libiconv=1.14=3
- libpng=1.6.26=0
- libsodium=1.0.10=0
- libtiff=4.0.6=7
- libxml2=2.9.4=3
- matplotlib=1.5.3=np111py27_2
- mkl=11.3.3=0
- ncurses=5.9=10
- numexpr=2.6.1=np111py27_1
- numpy=1.11.2=py27_0
- openssl=1.0.2k=0
- pandas=0.19.1=np111py27_0
- pango=1.40.1=0
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- patsy=0.4.1=py27_0
- pcre=8.39=0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pillow=3.4.2=py27_0
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.9=py27_0
- ptyprocess=0.5.1=py27_0
- pygments=2.1.3=py27_1
- pyparsing=2.1.10=py27_0
- pyqt=4.11.4=py27_4
- pytables=3.3.0=np111py27_0
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2016.7=py27_0
- pyyaml=3.12=py27_0
- pyzmq=16.0.1=py27_0
- qt=4.8.7=4
- readline=6.2=2
- scikit-learn=0.18.1=np111py27_0
- scipy<=1.4.1
- seaborn=0.7.1=py27_0
- setuptools=33.1.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_1
- sqlalchemy=1.1.5=py27_0
- sqlite=3.13.0=1
- ssl_match_hostname=3.5.0.1=py27_0
- statsmodels=0.6.1=np111py27_1
- tk=8.5.18=0
- tornado=4.4.2=py27_0
- traitlets=4.3.1=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- xlrd=1.0.0=py27_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.11=0
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - behaviorist (/local1/Code/behaviorist)==0.1.0
  - braintv-pilot (/local1/Projects/braintv_behavior_piloting)==0.1.0
  - click==6.7
  - dro (/local1/Code/dro)==0.1.0
  - h5py==2.6.0
  - imaging-behavior (/local1/Code/imaging_behavior)==0.0.5
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-core==4.2.0
  - mouse-info (/local1/Code/mouse_info)==0.3
  - nwb (/local1/Code/ainwb/ainwb)==1.0.0
  - prompt-toolkit==1.0.9
  - psychopy==1.82.1
  - pygraphviz==1.3.1
  - tables==3.3.0
  - transitions==0.4.2
  - figrid
  - squarify

