version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: setup virtualenv
          command: python3 -m venv venv
      - run:
          name: install dependencies
          command: |
            . venv/bin/activate
            pip install -U pip flake8
      - run:
          name: lint it up
          command: |
            . venv/bin/activate
            flake8 visual_behavior

  test-36:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: setup virtualenv
          command: python3 -m venv venv
      - run:
          name: install dependencies
          command: |
            . venv/bin/activate
            pip install -U pip tox
      - run:
          name: tox it up
          command: |
            . venv/bin/activate
            tox -e py36

workflows:
  version: 2
  basic:
    jobs:
      - lint
      - test-36
