# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  linting:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip flake8

      # lint code
      - run:
          name: lint code
          command: |
            . venv/bin/activate
            flake8 visual_behavior

  test-py27:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - py27-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt"}}
          # fallback to using the latest cache if no exact match is found
          - py27-dependencies-

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_dev.txt

      - save_cache:
          paths:
            - ./venv
          key: py27-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt"}}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-py36:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - py36-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt"}}
          # fallback to using the latest cache if no exact match is found
          - py36-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_dev.txt

      - save_cache:
          paths:
            - ./venv
          key: py36-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt"}}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - linting
      - test-py27
      - test-py36
