workflows:
  version: 2
  build:
    docker:
      - image: circleci/python:2.7.13
      - image: circleci/python:3.6.1
  steps:
    - checkout
    - run:
        name: set environments
        commands: |
          pyenv global 2.7.13 3.6.1
    - run:
        name: install dependencies
        command: |
          pip install -U pip tox
    - run:
        name: tox it up
        command:
          tox
