jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            pip install flake8
            flake8 visual_behavior
          name: lint it up

  test-37-pinned-allensdk: &linux-template
    parameters:
      pyversion:
        default: "3.7.7"
        type: string
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda create -q -n test-environment python=<<parameters.pyversion>> pip
            source activate test-environment
          name: Create conda test environment
      - run:
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            source activate test-environment
            pip install .[DEV]
          name: install dependencies
      - run:
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            source activate test-environment
            python -m pytest -m "not onprem"
          name: run tests

  test-36-pinned-allensdk:
    <<: *linux-template
    parameters:
      pyversion:
        default: "3.6.12"
        type: string

orbs:
  python: circleci/python@1.3.2
version: 2.1
workflows:
  basic:
    jobs:
      - lint
      - test-36-pinned-allensdk
      - test-37-pinned-allensdk
