static_full_field_gratings:
    stage: static_full_field_gratings
    stimulus: full_screen_square_wave
    delta_oris: [90]
        
    rewardvol: 0.01
    task_mode: training
    catch_frequency: 0.5

    lick_detect_training_enabled: true
    lick_detect_training_mode: single
    lick_detect_training_block_length: [8,12]

    whitenoise_on_timeout: false
    blankscreen_on_timeout: false
    blankscreen_duration: 1

    max_number_trial_repeats: 5

    volumelimit: 1.5

    stim_duration: 0.2
    blank_duration_range: [0.0,0.0]
    SF: 0.04

    initial_blank: 0
    delta_minimum: 2
    stimulus_distribution: uniform
    trial_duration: 4.5
    response_window: [0.15,1]

    warmup_trials: 5

    frame_interval_plot: none
    Duration: 60

static_windowed_gratings:
    stage: static_windowed_gratings

static_windowed_gratings_flash_500ms:
    stage: static_windowed_gratings_flash_500ms
    Duration: 60
